### ISSUE TITLE
The read streams continue to run even after the sparksession is stopped

### ISSUE THREAD

**Issue by archetana** [spark-jobserver/spark-jobserver#1119]
Used Spark version: v2.3.1

Used Spark Job Server version: v0.8.0
(Released version, git branch or docker image version)

Deployed mode: cluster on YARN
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)

Wrong Behaviour: The read streams continue to run even after the sparksession is stopped

Steps to reproduce:
1.Start a job with read streams 
Example: 
spark
  .readStream
  .format("kafka")
  .option("kafka.bootstrap.servers", "host1:port1,host2:port2")
  .option("subscribe", "topic1")
  .load()

2. Kill the job, the read stream remains open and reader continues  to poll

**Comment by thoHeinze** [comment]
Hi @archetana, 

can you please describe a bit more in detail what you mean by "the read stream remains open" ? 
Spark has a certain behaviour, which SJS does not change:
1. Currently running batches will be continued to process, after you send the DELETE request.
2. If a lot of batches have been scheduled and not processed ( e.g. because your job is overloaded), all these batches will be processed before shutting down.

Overall, you can expect your job is not immediately terminated, however after a few minutes it should be stopped.

**Comment by archetana** [comment]
Hi @thoHeinze ,

Attaching the logs, even after stopping the context, the stream microbatch continues. I understand that the expectation is that the streams shut down when the context is closed, it looks like an issue with Spark . In our setup we added a couple of lines while shutting the context to query and stop the streams before stopping the context.
[server_start_1.log](https://github.com/spark-jobserver/spark-jobserver/files/2455325/server_start_1.log)

**Comment by Nibooor** [comment]
Issue has been addressed already. Thank you for the contribution!
