### ISSUE TITLE
Spark Job Server throwing error in mesos client mode

### ISSUE THREAD

**Issue by sj83** [spark-jobserver/spark-jobserver#1160]
**Used Spark version**
2.3.2
**Used Spark Job Server version**
(Released version, git branch or docker image version)
0.9.0-SNAPSHOT
**Deployed mode**
Mesos client mode

I am getting an error when I try to create the context with mesos client mode.:
Can not create a Path from an empty string

Can someone help with the issue. I have configured the application.conf file as per the instruction.

**Comment by thoHeinze** [comment]
@sj83 Can you please share yor jobserver configuration, the logs and the exact error message?

**Comment by sj83** [comment]
@thoHeinze I was able to resolve the issue, but I had a question regarding how Spark Job Server is behaving. I am not sure where exactly should I post the question so i will ask here and you can please let me know if it needs to be posted somewhere else and I will do that.

So we are testing one aspect of the Job Server where say we use the rest-api to submit a job and say if the job server crashes and then we recover it will we have the correct status of the spark job. So to replicate this I I pointed master in config file to stand alone spark master. 
Started the job  server
Submitted the job
Stopped the job server
I clearly see in the logs that the server is shutdown but I still see running logs where it says the job was completed and the status of the job is in correct state. This is exactly what we need but wanted to figure out how this was working even though the Job server was shutdown(a background processing has a hook to the standalone spark master?)? Also I doubt if this scenario will work if the machine goes down.

**Comment by bsikander** [comment]
It is a bit late but maybe it helps.

Both Jobserver master and slaves (driver processes) are connected to external store like DB/C* etc. 
Even though Jobserver master is down, the slaves (driver processes) are still connected to the store. When the job completes, the message is sent from JobManagerActor to JobStatusActor (both are running on driver), this message is `JobFinished`. JobStatusActor updates the DB/store to reflect the new state.

Further, there are 2 cases after this
- If the context is a "adhoc" context then as soon as the job finished, the context will also kill itself. During this kill process, JobStatusActor is also killed and its `postStop` event is fired which cleans the state in DB. This also doesn't need JobServer master.
- If it is a normal context then you need to stop it through spark UI or Jobserver master UI and clean up will happen at that point.

Even though all of this okay but there are cornor cases e.g. your context/driver goes OOM or is killed due to some other reason, then cleanup cannot happen on driver level. Then Jobserver master kicks in does the cleanup either at jobserver master startup or in `Terminated` event.
