### ISSUE TITLE
Context STATE is always STARTED and dosent change its state  (0.9.0)

### ISSUE THREAD

**Issue by AadhiKat** [spark-jobserver/spark-jobserver#1188]
Hi , 

I have already created a context with name SJS_512_MB_shared_prioritized@1 and somehow its state is always in STARTED state . When I get all the available contexts , this context is not shown in the list of contexts..

So , when I tried creating the context with the same name , I am getting an error that 

```
HTTP/1.1 400 Bad Request
Server: spray-can/1.3.4
Date: Tue, 16 Apr 2019 10:10:45 GMT
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=UTF-8
Content-Length: 85

{
  "status": "ERROR",
  "result": "context SJS_512_MB_shared_prioritized@1 exists" 

```

So ,  on querying the CONTEXTS table in SJS-0.9.0 . This is the result.

```

ID                                   | 4f6ec7ab-c00b-469c-b3de-a56de79c1231
NAME                            | SJS_512_MB_shared_prioritized@1
CONFIG                        | {"context":{"name":"SJS_512_MB_shared_prioritized@1"},"context-factory":"spark.jobserver.context.SessionContextFactory","context-init-timeout":"60s","forked-jvm-init-timeout":"30s","is-adh
oc":"false","launcher":{"spark":{"driver":{"memory":"1g"}}},"memory-per-node":"512M","num-cpu-cores":"1","passthrough":{"spark":{"driver":{"allowMultipleContexts":true,"extraJavaOptions":"-Dorg.xerial.sna
ppy.tempdir=/home/sas/zdpas/spark/snappydata"},"executor":{"extraJavaOptions":"-Dorg.xerial.snappy.tempdir=/home/sas/zdpas/spark/snappydata"}}},"python":{"executable":"python","paths":[]},"streaming":{"ba
tch_interval":1000,"stopGracefully":true,"stopSparkContext":true}}
ACTOR_ADDRESS       | 
START_TIME                | 2019-04-15 19:01:36.457
END_TIME                    | 
STATE                          | STARTED
ERROR                         | 
```

Though it will work if the context is deleted , can you please tell me if at all why that had happened ?

**Comment by bsikander** [comment]
The context is in STARTED state because it failed to startup. If the POST /context would succeed then you will see the context state as RUNNING.

When user submits POST /contexts, we put the context in STARTED state and use SparkLauncher to start spin up a new JVM which runs your context inside. When the JVM comes up, it communicates back with jobserver and jobserver tells the JVM/context to initialize itself. Once the initialization is done, the context state is moved to RUNNING.

In your case, it seems that the context JVM is not coming up or not communicating back. Please check logs for context/driver.
