### ISSUE TITLE
[Question] Does Spark-Jobserver invoke a process for each context created 

### ISSUE THREAD

**Issue by ArunNachiappan** [spark-jobserver/spark-jobserver#1189]
**Used Spark version** 2.4.0

**Used Spark Job Server version** 0.8.0

**Deployed mode** Cluster

 
I am using jobserver to create a persistent context and submit multiple jobs to it. 
I have the jobserver deployed in a node exclusive of the cluster but accessible. 
For each context I create there is process added [SparkSubmit] , is this the actual behaviour ? 
After creating N contexts there are N+1 processes with SparkSubmit

`` /usr/local/jdk/bin/java -cp /usr/local/spark/conf/:/usr/local/spark/jars/* org.apache.spark.deploy.SparkSubmit --master spark://xxx.xx.xx.xxx:6066,xxx.xx.xx.xxx:6066,xxx.xx.xx.xxx:6066 --deploy-mode cluster --conf spark.driver.memory=1G --conf spark.yarn.submit.waitAppCompletion=false --conf spark.executor.extraJavaOptions=-Dlog4j.configuration=/usr/local/job-server/log4j-cluster.properties --conf spark.driver.extraJavaOptions=-XX:+UseConcMarkSweepGC          -verbose:gc -XX:+PrintGCTimeStamps          -XX:MaxPermSize=512m          -XX:+CMSClassUnloadingEnabled  -XX:MaxDirectMemorySize=512M            -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Dlog4j.configuration=/usr/local/job-server/log4j-cluster.properties -Dspark.executor.uri=/home/spark/spark-1.6.0.tar.gz   --class spark.jobserver.JobManager /usr/local/job-server/spark-job-server.jar akka.tcp://JobServer@xxx.xx.xx.xxx:41252 jobManager-ee-a0ee-9b2a1b881c1a /usr/local/job-server/local.conf ``

Killing these processes, does not affect the behaviour at all. Jobs are processed successfully.

Also what are these configurations for : **job-number-cpus**  and  **max-jobs-per-context**  ?

Is it possible to create and use multiple persistent long **running contexts in client mode** ?

**Comment by bsikander** [comment]
In cluster mode, when you try to start a context a JVM (process) with name SparkSubmit will be started on Jobserver VM. But it is a short lived process and as soon as the job is submitted to spark cluster at xxx.xx.xx.xxx:6066, this process should finish automatically. If it is not going away the there is some issue.

They are N +1 because Jobserver itself uses spark-submit to start itself so its process name is also SparkSubmit.

>> Killing these processes, does not affect the behaviour at all. Jobs are processed successfully.
As mentioned above, they should be finished automatically. Their live is generally 5-10s only.

>> Is it possible to create and use multiple persistent long running contexts in client mode ?
Yes, it is possible.

>> Also what are these configurations for : job-number-cpus and max-jobs-per-context ?
`job-number-cpus`  = this seems useless. Not used anymore. Should be removed. Feel free to contribute.
`max-jobs-per-context` = In batch mode, within 1 context, you can launch multiple jobs. This property controls the max amount of jobs within 1 context
