### ISSUE TITLE
Creating war file out of job server

### ISSUE THREAD

**Issue by kavuri** [spark-jobserver/spark-jobserver#122]
Is creating a war file out of the job server supported? If not, what could be the steps to do so?

**Comment by sidahmedbenkhaoua** [comment]
you can use rest requtte to call job

**Comment by kavuri** [comment]
I mean, I would like to package the job-server as a war file so that I can deploy it in a container like tomcat / jboss etc.

**Comment by velvia** [comment]
Hi Sateesh,

This is not currently supported, and would be nontrivial as Spray, the
underlying web framework, is not based on the Servlet API.    There is a
spray-servlet package, and I could give you pointers on how to implement
said support, but it might take a couple days.

thanks,
Evan


On Sun, Apr 12, 2015 at 9:44 AM, Sateesh Kavuri <notifications@github.com>
wrote:

> I mean, I would like to package the job-server as a war file so that I can
> deploy it in a container like tomcat / jboss etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/122#issuecomment-92086140>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by kavuri** [comment]
Couple of days is reasonable. Can you please provide the pointers for the
same. Guess you can help out to unravel is when stuck

**Comment by velvia** [comment]
Sateesh,

Have a look at these links:

http://spray.io/documentation/1.2.2/spray-servlet/
http://www.javacodegeeks.com/2015/03/building-a-war-with-spray-servlet.html

I would advise creating a new SBT project, maybe called "jobserver-war",
which has the additional files (boot class, web.xml, etc.) so that to
minimize change to the normal project.  Otherwise there might be two main
classes and two ways of starting the web service which would be confusing.

Best of luck!

On Mon, Apr 13, 2015 at 6:27 PM, Sateesh Kavuri <notifications@github.com>
wrote:

> Couple of days is reasonable. Can you please provide the pointers for the
> same. Guess you can help out to unravel is when stuck
> On 14 Apr 2015 05:36, "Evan Chan" <notifications@github.com> wrote:
>
> > Hi Sateesh,
> >
> > This is not currently supported, and would be nontrivial as Spray, the
> > underlying web framework, is not based on the Servlet API. There is a
> > spray-servlet package, and I could give you pointers on how to implement
> > said support, but it might take a couple days.
> >
> > thanks,
> > Evan
> >
> >
> > On Sun, Apr 12, 2015 at 9:44 AM, Sateesh Kavuri <
> notifications@github.com>
> > wrote:
> >
> > > I mean, I would like to package the job-server as a war file so that I
> > can
> > > deploy it in a container like tomcat / jboss etc.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/spark-jobserver/spark-jobserver/issues/122#issuecomment-92086140
> > >
> > > .
> > >
> >
> >
> >
> > --
> > If you are free, you need to free somebody else.
> > If you have some power, then your job is to empower somebody else.
> > --- Toni Morrison
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/spark-jobserver/spark-jobserver/issues/122#issuecomment-92542561
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/122#issuecomment-92554112>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by noorul** [comment]
Closing this.
