### ISSUE TITLE
Kill pending yarn application when timeout occur

### ISSUE THREAD

**Issue by TianTian106** [spark-jobserver/spark-jobserver#1274]
**Used Spark version**
2.4
**Used Spark Job Server version**
0.8.0
**Deployed mode**
cluster on YARN

**Actual (wrong) behavior**
When yarn resource is full, the application is UNASSIGNED. 
State: ACCEPTED
FinalStatus: UNDEFINED
When resource is full for a long time, the POST jobs request will get a timeout exception, but yarn application is still there and will be running when resource is enough.
Can I kill the pending yarn application when spark-jobserver return a timeout exception because of insufficient resource ?

Thanks for helping~~

**Comment by bsikander** [comment]
You are using an old version of jobserver. In 0.9.0, this problem was fixed.
https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/main/scala/spark/jobserver/AkkaClusterSupervisorActor.scala#L180

As soon as the jobserver master figures out that driver did not connect back within a timeout, it marks the context in ERROR state. Later when driver gets the resources and tries to communicate with jobserver master, the master kills the driver immediately and resources are released.

Closing the issue. Please reopen if you still have problem.

**Comment by TianTian106** [comment]
Many thanks! 😃
