### ISSUE TITLE
Update jar without restart context

### ISSUE THREAD

**Issue by v-gerasimov** [spark-jobserver/spark-jobserver#130]
Hi!

I upload jar on spark-jobserver and start context by api. If I update jar and upload it again (with same name), I need restart context for working with updated jar. Can I update jar without restart context?

**Comment by velvia** [comment]
Hi, no you cannot, because of the fundamental limitation of classloaders in
the JVM...... any class that is loaded already, will not get reinitialized
(unless you do nasty classpath renaming tricks, etc.).  Sorry.

On Fri, Apr 24, 2015 at 4:17 AM, v-gerasimov <notifications@github.com>
wrote:

> Hi.
>
> I upload jar on spark-jobserver and start context by api. If I update jar
> and upload it again (with same name), I need restart context for working
> with updated jar. Can I update jar on context without restart context?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/130>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by v-gerasimov** [comment]
Thank you, Evan.

**Comment by amittonge** [comment]
I am also facing same issue. Do you found any workaround for this problem, please share.
