### ISSUE TITLE
Not able to build jobserver image Mesos seems to be broken.

### ISSUE THREAD

**Issue by shikhar7** [spark-jobserver/spark-jobserver#1316]
RUN echo "deb http://repos.mesosphere.io/ubuntu/ xenial main" > /etc/apt/sources.list.d/mesosphere.list && \
                apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF && \
                apt-get -y update && \
                apt-get -y install mesos && \
                apt-get clean && \
                mkdir -p /database

The above lines in  dockerfile is giving error.Dependency for mesos are missing,

```
ERROR: 
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mesos : Depends: libcurl3 but it is not installable
         Recommends: zookeeper but it is not going to be installed
         Recommends: zookeeperd but it is not going to be installed
         Recommends: zookeeper-bin but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by valan4ik** [comment]
Docker image should be fixed now. I will close the issue, please reopen it if the problem persists for you.

**Comment by HenrryVargas** [comment]
Hello

Same error.

I'am usining this:

# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG BASE_CONTAINER=jupyter/scipy-notebook
FROM $BASE_CONTAINER

USER root

# Spark dependencies
ENV APACHE_SPARK_VERSION 2.4.4
ENV HADOOP_VERSION 2.9.2

RUN apt-get -y update && \
    apt-get install --no-install-recommends -y openjdk-8-jre-headless ca-certificates-java && \
    rm -rf /var/lib/apt/lists/*

# RUN cd /tmp && \
#     wget -q http://mirrors.ukfast.co.uk/sites/ftp.apache.org/spark/spark-${APACHE_SPARK_VERSION}/spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
#     echo "2E3A5C853B9F28C7D4525C0ADCB0D971B73AD47D5CCE138C85335B9F53A6519540D3923CB0B5CEE41E386E49AE8A409A51AB7194BA11A254E037A848D0C4A9E5 *spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz" | sha512sum -c - && \
#     tar xzf spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz -C /usr/local --owner root --group root --no-same-owner && \
#     rm spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz
# RUN cd /usr/local && ln -s spark-${APACHE_SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} spark
RUN cd /tmp && \
    wget --no-check-certificate https://archive.apache.org/dist/spark/spark-${APACHE_SPARK_VERSION}/spark-${APACHE_SPARK_VERSION}-bin-without-hadoop.tgz && \
    tar xzf spark-${APACHE_SPARK_VERSION}-bin-without-hadoop.tgz -C /usr/local --owner root --group root --no-same-owner && \
    rm spark-${APACHE_SPARK_VERSION}-bin-without-hadoop.tgz
RUN cd /usr/local && ln -s spark-${APACHE_SPARK_VERSION}-bin-without-hadoop spark

# Install hadoop
# https://archive.apache.org/dist/hadoop/core/hadoop-2.9.2/hadoop-2.9.2.tar.gz
RUN cd /tmp && \
    wget --no-check-certificate https://archive.apache.org/dist/hadoop/core/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz && \
    tar xzf hadoop-${HADOOP_VERSION}.tar.gz -C /usr/local --owner root --group root --no-same-owner && \
    rm hadoop-${HADOOP_VERSION}.tar.gz
RUN cd /usr/local && ln -s hadoop-${HADOOP_VERSION} hadoop

# Mesos dependencies
# Install from the Xenial Mesosphere repository since there does not (yet)
# exist a Bionic repository and the dependencies seem to be compatible for now.
COPY config/mesos.key /tmp/



#RUN apt-get -y update && \
 #   apt-get install  --no-install-recommends -y gnupg && \
 #   apt-key add /tmp/mesos.key && \
 #   echo "deb http://repos.mesosphere.io/ubuntu xenial main" > /etc/apt/sources.list.d/mesosphere.list && \
 #   apt-get -y update && \
 #   apt-get --no-install-recommends -y install mesos=1.2\* && \
 #   apt-get purge --auto-remove -y gnupg && \
 #   rm -rf /var/lib/apt/lists/*

RUN apt-get -y update && \
    apt-get install  --no-install-recommends -y gnupg && \
    apt-key add /tmp/mesos.key && \
    echo "deb http://repos.mesosphere.io/ubuntu xenial main" > /etc/apt/sources.list.d/mesosphere.list


RUN apt-get -y update && \
    apt-get --no-install-recommends -y install -f mesos=1.2\* && \
    apt-get purge --auto-remove -y gnupg && \
    rm -rf /var/lib/apt/lists/*

# Spark and Mesos config
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/jre
ENV SPARK_HOME /usr/local/spark
ENV PATH $PATH:$SPARK_HOME/bin
ENV HADOOP_HOME /usr/local/hadoop
ENV PATH $PATH:$HADOOP_HOME/bin
ENV LD_LIBRARY_PATH $HADOOP_HOME/lib/native
ENV SPARK_DIST_CLASSPATH $HADOOP_HOME/etc/hadoop:$HADOOP_HOME/share/hadoop/common/lib/*:$HADOOP_HOME/share/hadoop/common/*:$HADOOP_HOME/share/hadoop/hdfs:$HADOOP_HOME/share/hadoop/hdfs/lib/*:$HADOOP_HOME/share/hadoop/hdfs/*:$HADOOP_HOME/share/hadoop/yarn:$HADOOP_HOME/share/hadoop/yarn/lib/*:$HADOOP_HOME/share/hadoop/yarn/*:$HADOOP_HOME/share/hadoop/mapreduce/lib/*:$HADOOP_HOME/share/hadoop/mapreduce/*:/usr/local/hadoop/contrib/capacity-scheduler/*.jar
ENV PYTHONPATH $SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.7-src.zip
ENV MESOS_NATIVE_LIBRARY /usr/local/lib/libmesos.so
ENV SPARK_OPTS --driver-java-options=-Xms1024M --driver-java-options=-Xmx4096M --driver-java-options=-Dlog4j.logLevel=info


# Setup AWS S3 dependencies
ENV AWS_SDK_VERSION 1.11.524
RUN cd $SPARK_HOME/jars && \
    wget -q https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_VERSION}/hadoop-aws-${HADOOP_VERSION}.jar && \
    wget -q https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar && \
    wget -q https://repo1.maven.org/maven2/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar && \
    wget -q https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-core/${AWS_SDK_VERSION}/aws-java-sdk-core-${AWS_SDK_VERSION}.jar && \
    wget -q https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk/${AWS_SDK_VERSION}/aws-java-sdk-${AWS_SDK_VERSION}.jar && \
    wget -q https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-kms/${AWS_SDK_VERSION}/aws-java-sdk-kms-${AWS_SDK_VERSION}.jar && \
    wget -q https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-s3/${AWS_SDK_VERSION}/aws-java-sdk-s3-${AWS_SDK_VERSION}.jar && \
    wget -q https://jdbc.postgresql.org/download/postgresql-42.2.12.jar && \
    wget -q https://github.com/DataSystemsLab/GeoSpark/releases/download/1.3.1-spark-2.3/geospark-1.3.1.jar && \
    wget -q https://github.com/DataSystemsLab/GeoSpark/releases/download/1.3.1-spark-2.3/geospark-sql_2.3-1.3.1.jar && \
    wget -q https://github.com/DataSystemsLab/GeoSpark/releases/download/1.3.1-spark-2.3/geospark-viz_2.3-1.3.1.jar

# RSpark config
ENV R_LIBS_USER $SPARK_HOME/R/lib
RUN fix-permissions $R_LIBS_USER

# R pre-requisites
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    fonts-dejavu \
    gfortran \
    gcc && \
    rm -rf /var/lib/apt/lists/*

USER $NB_UID

# R packages
RUN conda install --quiet --yes \
    'r-base=3.6.1' \
    'r-ggplot2=3.2*' \
    'r-irkernel=1.0*' \
    'r-rcurl=1.95*' \
    'r-sparklyr=1.0*' \
    && \
    conda clean --all -f -y && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

# Apache Toree kernel
RUN pip install --no-cache-dir \
    https://dist.apache.org/repos/dist/release/incubator/toree/0.3.0-incubating/toree-pip/toree-0.3.0.tar.gz \
    && \
    jupyter toree install --sys-prefix && \
    rm -rf /home/$NB_USER/.local && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER 

# Spylon-kernel
RUN conda install --quiet --yes 'spylon-kernel=0.4*' && \
    conda clean --all -f -y && \
    python -m spylon_kernel install --sys-prefix && \
    rm -rf /home/$NB_USER/.local && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

# Install pyarrow
RUN conda install --quiet -y 'pyarrow' && \
    conda clean --all -f -y && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

#ABXDA
USER root

RUN pip install --no-cache-dir \
    html2text \
    psycopg2-binary \
    minio \
    newspaper3k==0.2.8 \
    altair \
    vega_datasets \
    geospark \
    geopandas

#Configure
#master
ADD  config/master.sh /
RUN chmod +x /master.sh

ENV SPARK_MASTER_PORT 7077
ENV SPARK_MASTER_WEBUI_PORT 8080
ENV SPARK_MASTER_LOG /usr/local/spark/logs

EXPOSE 8080 7077 6066

#master
ADD  config/worker.sh /
RUN chmod +x /worker.sh

ENV SPARK_WORKER_WEBUI_PORT 8081
ENV SPARK_WORKER_LOG /spark/logs
ENV SPARK_MASTER "spark://spark-master:7077"

EXPOSE 8081

An the rror is :

**[ 9/21] RUN apt-get -y update &&     apt-get --no-install-recommends -y install -f mesos=1.2* &&     apt-get purge --auto-remove -y gnupg &&     rm -rf /var/lib/apt/lists/*:
#14 0.534 Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
#14 0.670 Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
#14 1.140 Get:5 http://repos.mesosphere.com/ubuntu xenial InRelease [5,275 B]
#14 1.429 Get:6 http://repos.mesosphere.com/ubuntu xenial/main amd64 Packages [20.6 kB]
#14 1.460 Fetched 25.9 kB in 1s (24.2 kB/s)
#14 1.460 Reading package lists...
#14 2.329 Reading package lists...
#14 3.039 Building dependency tree...
#14 3.195 Reading state information...
#14 3.270 Some packages could not be installed. This may mean that you have
#14 3.270 requested an impossible situation or if you are using the unstable
#14 3.270 distribution that some required packages have not yet been created
#14 3.270 or been moved out of Incoming.
#14 3.270 The following information may help to resolve the situation:
#14 3.270
#14 3.270 The following packages have unmet dependencies:
#14 3.380  mesos : Depends: libcurl3 but it is not installable
#14 3.404 E: Unable to correct problems, you have held broken packages.**

**Comment by HenrryVargas** [comment]
Hi

Same error. I am using this dockerfile:

ARG BASE_CONTAINER=jupyter/scipy-notebook
FROM $BASE_CONTAINER

USER root


ENV APACHE_SPARK_VERSION 2.4.4
ENV HADOOP_VERSION 2.9.2

RUN apt-get -y update && \
    apt-get install --no-install-recommends -y openjdk-8-jre-headless ca-certificates-java && \
    rm -rf /var/lib/apt/lists/*

RUN cd /tmp && \
    wget --no-check-certificate https://archive.apache.org/dist/spark/spark-${APACHE_SPARK_VERSION}/spark-${APACHE_SPARK_VERSION}-bin-without-hadoop.tgz && \
    tar xzf spark-${APACHE_SPARK_VERSION}-bin-without-hadoop.tgz -C /usr/local --owner root --group root --no-same-owner && \
    rm spark-${APACHE_SPARK_VERSION}-bin-without-hadoop.tgz
RUN cd /usr/local && ln -s spark-${APACHE_SPARK_VERSION}-bin-without-hadoop spark


RUN cd /tmp && \
    wget --no-check-certificate https://archive.apache.org/dist/hadoop/core/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz && \
    tar xzf hadoop-${HADOOP_VERSION}.tar.gz -C /usr/local --owner root --group root --no-same-owner && \
    rm hadoop-${HADOOP_VERSION}.tar.gz
RUN cd /usr/local && ln -s hadoop-${HADOOP_VERSION} hadoop


COPY config/mesos.key /tmp/



RUN apt-get -y update && \
    apt-get install  --no-install-recommends -y gnupg && \
    apt-key add /tmp/mesos.key && \
    echo "deb http://repos.mesosphere.io/ubuntu xenial main" > /etc/apt/sources.list.d/mesosphere.list


RUN apt-get -y update && \
    apt-get --no-install-recommends -y install -f mesos=1.2\* && \
    apt-get purge --auto-remove -y gnupg && \
    rm -rf /var/lib/apt/lists/*


ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/jre
ENV SPARK_HOME /usr/local/spark
ENV PATH $PATH:$SPARK_HOME/bin
ENV HADOOP_HOME /usr/local/hadoop
ENV PATH $PATH:$HADOOP_HOME/bin
ENV LD_LIBRARY_PATH $HADOOP_HOME/lib/native
ENV SPARK_DIST_CLASSPATH $HADOOP_HOME/etc/hadoop:$HADOOP_HOME/share/hadoop/common/lib/*:$HADOOP_HOME/share/hadoop/common/*:$HADOOP_HOME/share/hadoop/hdfs:$HADOOP_HOME/share/hadoop/hdfs/lib/*:$HADOOP_HOME/share/hadoop/hdfs/*:$HADOOP_HOME/share/hadoop/yarn:$HADOOP_HOME/share/hadoop/yarn/lib/*:$HADOOP_HOME/share/hadoop/yarn/*:$HADOOP_HOME/share/hadoop/mapreduce/lib/*:$HADOOP_HOME/share/hadoop/mapreduce/*:/usr/local/hadoop/contrib/capacity-scheduler/*.jar
ENV PYTHONPATH $SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.7-src.zip
ENV MESOS_NATIVE_LIBRARY /usr/local/lib/libmesos.so
ENV SPARK_OPTS --driver-java-options=-Xms1024M --driver-java-options=-Xmx4096M --driver-java-options=-Dlog4j.logLevel=info



ENV AWS_SDK_VERSION 1.11.524
RUN cd $SPARK_HOME/jars && \
    wget -q https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_VERSION}/hadoop-aws-${HADOOP_VERSION}.jar && \
    wget -q https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar && \
    wget -q https://repo1.maven.org/maven2/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar && \
    wget -q https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-core/${AWS_SDK_VERSION}/aws-java-sdk-core-${AWS_SDK_VERSION}.jar && \
    wget -q https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk/${AWS_SDK_VERSION}/aws-java-sdk-${AWS_SDK_VERSION}.jar && \
    wget -q https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-kms/${AWS_SDK_VERSION}/aws-java-sdk-kms-${AWS_SDK_VERSION}.jar && \
    wget -q https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-s3/${AWS_SDK_VERSION}/aws-java-sdk-s3-${AWS_SDK_VERSION}.jar && \
    wget -q https://jdbc.postgresql.org/download/postgresql-42.2.12.jar && \
    wget -q https://github.com/DataSystemsLab/GeoSpark/releases/download/1.3.1-spark-2.3/geospark-1.3.1.jar && \
    wget -q https://github.com/DataSystemsLab/GeoSpark/releases/download/1.3.1-spark-2.3/geospark-sql_2.3-1.3.1.jar && \
    wget -q https://github.com/DataSystemsLab/GeoSpark/releases/download/1.3.1-spark-2.3/geospark-viz_2.3-1.3.1.jar


ENV R_LIBS_USER $SPARK_HOME/R/lib
RUN fix-permissions $R_LIBS_USER


RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    fonts-dejavu \
    gfortran \
    gcc && \
    rm -rf /var/lib/apt/lists/*

USER $NB_UID


RUN conda install --quiet --yes \
    'r-base=3.6.1' \
    'r-ggplot2=3.2*' \
    'r-irkernel=1.0*' \
    'r-rcurl=1.95*' \
    'r-sparklyr=1.0*' \
    && \
    conda clean --all -f -y && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER


RUN pip install --no-cache-dir \
    https://dist.apache.org/repos/dist/release/incubator/toree/0.3.0-incubating/toree-pip/toree-0.3.0.tar.gz \
    && \
    jupyter toree install --sys-prefix && \
    rm -rf /home/$NB_USER/.local && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER 


RUN conda install --quiet --yes 'spylon-kernel=0.4*' && \
    conda clean --all -f -y && \
    python -m spylon_kernel install --sys-prefix && \
    rm -rf /home/$NB_USER/.local && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER


RUN conda install --quiet -y 'pyarrow' && \
    conda clean --all -f -y && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER


USER root

RUN pip install --no-cache-dir \
    html2text \
    psycopg2-binary \
    minio \
    newspaper3k==0.2.8 \
    altair \
    vega_datasets \
    geospark \
    geopandas


ADD  config/master.sh /
RUN chmod +x /master.sh

ENV SPARK_MASTER_PORT 7077
ENV SPARK_MASTER_WEBUI_PORT 8080
ENV SPARK_MASTER_LOG /usr/local/spark/logs

EXPOSE 8080 7077 6066


ADD  config/worker.sh /
RUN chmod +x /worker.sh

ENV SPARK_WORKER_WEBUI_PORT 8081
ENV SPARK_WORKER_LOG /spark/logs
ENV SPARK_MASTER "spark://spark-master:7077"

EXPOSE 8081


And show me this error:

[ 9/21] RUN apt-get -y update &&     apt-get --no-install-recommends -y install -f mesos=1.2* &&     apt-get purge --auto-remove -y gnupg &&     rm -rf /var/lib/apt/lists/*:
#14 0.534 Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
#14 0.670 Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
#14 1.140 Get:5 http://repos.mesosphere.com/ubuntu xenial InRelease [5,275 B]
#14 1.429 Get:6 http://repos.mesosphere.com/ubuntu xenial/main amd64 Packages [20.6 kB]
#14 1.460 Fetched 25.9 kB in 1s (24.2 kB/s)
#14 1.460 Reading package lists...
#14 2.329 Reading package lists...
#14 3.039 Building dependency tree...
#14 3.195 Reading state information...
#14 3.270 Some packages could not be installed. This may mean that you have
#14 3.270 requested an impossible situation or if you are using the unstable
#14 3.270 distribution that some required packages have not yet been created
#14 3.270 or been moved out of Incoming.
#14 3.270 The following information may help to resolve the situation:
#14 3.270
#14 3.270 The following packages have unmet dependencies:
#14 3.380  mesos : Depends: libcurl3 but it is not installable
#14 3.404 E: Unable to correct problems, you have held broken packages.
