### ISSUE TITLE
SparkSessionJobs fail with "Invalid job type for this context"

### ISSUE THREAD

**Issue by murraytodd** [spark-jobserver/spark-jobserver#1340]
Using 0.10.0 in local standalone mode (Spark 2.4.4), I'm trying to work out a basic WordCount example, but I'm trying to use the SparkSessionJob as my base. When I try to run it, the job fails with the message "Invalid job type for this context".

The code is simply this:

```
object WordCountSessionExample extends SparkSessionJob {
  override type JobData = String
  override type JobOutput = Long

  override def runJob(spark: SparkSession, runtime: JobEnvironment, data: JobData): JobOutput = {
    val lines = spark.read.textFile(data)
    lines.rdd.map(_.split("\\W+").length) // Count words on each line parsed by whitespace
      .aggregate(0L)((a,l) => a + l, (a,b) => a + b)
  }

  override def validate(spark: SparkSession, runtime: JobEnvironment, config: Config): Or[JobData, Every[ValidationProblem]] = {
    Try(config.getString("wc.path")) match {
      case Success(path) => Good(path)
      case Failure(exception) => Bad(One(SingleProblem("wc.path not found")))
    }
  }
}
```

I upload the JAR, and try to run the example with 
`curl -d "wc.path = /spark/" "localhost:8090/jobs?appName=test&classPath=aps.WordCountSessionExample"`

I have an near identical example that just extends `spark.jobserver.api.SparkJob` that runs as expected, so I think I can rule out configuration, etc.

Am I missing anything obvious?

**Comment by valan4ik** [comment]
Hi @murraytodd ,

There are different type of the contexts. If you use `SparkSessionJob` then you need to create a `SessionContext` before submitting a job. Please check: https://github.com/spark-jobserver/spark-jobserver#new-sparkjob-api-with-spark-v21

Extending `spark.jobserver.api.SparkJob` works, because it is a default context type. This context type is used if you didn't specify which context should be used during the `POST /contexts` request or if you posted a job without creating a context in advance.

**Comment by murraytodd** [comment]
Thanks for explaining that. I would have never figured that out otherwise. I didn't realize there were different types of contexts. I'll try this tomorrow and will close the issue.
