### ISSUE TITLE
sbt spends too much time in resolving/updating

### ISSUE THREAD

**Issue by mdespriee** [spark-jobserver/spark-jobserver#186]
When I do a reStart or something, sbt spends a long time going through all dependencies to check for update (I guess), and sometimes it take a very long time to finish "Resolving org.apache.hadoop#hadoop-yarn;2.2.0 .."

Is there any way to skip all these updates ?

**Comment by velvia** [comment]
Hmm. It should only have to do that the first time.  Once downloaded shouldn't have to do that. You could skip the horribly big Hive dep tree by doing job-server/reStart instead of job-server-extras. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by noorul** [comment]
I also faced this issue. But job-server/reStop and job-server/reStart is fast enough. Can we close this issue?
