### ISSUE TITLE
Possible job cache bug

### ISSUE THREAD

**Issue by JoeYang** [spark-jobserver/spark-jobserver#218]
I uploaded 2 jars to spark job server named app_1 and app_2. The job class has the same class path with some modifications. 

Then I submitted this 2 jobs to the job server:

job_1 = ?appName=app_1&classPath=com.test.job&context=context_1
job_2 = ?appName=app_2&classPath=com.test.job&context=context_1

It appears to the log that job_2 was exactly the same as job_1 ignoring the changes I made to it. 

To verify I did not upload the wrong jar, I restarted the job server and I reversed the order of job submission,

job_1 = ?appName=app_1&classPath=com.test.job&context=context_1
job_2 = ?appName=app_2&classPath=com.test.job&context=context_1,

and this time job_1 was identical to job_2. 

Digging into the source code it seems that the jobJar was cached. I am wondering if there are anything I did that's not supposed to be done. I have a feeling the job cache might ignore the appName.

**Comment by velvia** [comment]
Hi @JoeYang 

So my understanding is that you uploaded two nearly identical jars to the same context, and submitted both jobs, is that right?

What is happening is this.  Each SparkContext has one custom classloader.  In the JVM you cannot update JAR code live -- it's not a job server limitation, but a fundamental JVM limitation.  Once you load in the classes for jar1, you cannot try to load in newer versions of those classes, because the classloader will keep using the class names that are already loaded.

Hope I'm not misunderstanding....

**Comment by JoeYang** [comment]
it all makes sense now. Thank you so much @velvia
