### ISSUE TITLE
allow non-computed named RDDs

### ISSUE THREAD

**Issue by mjanson** [spark-jobserver/spark-jobserver#247]
Is there a reason why only *computed* named RDDs are currently supported?

We have an extremely large (impossible to load into memory/disk) parquet dataset in AWS S3 which requires several minutes just to scan all partition files.  We would like to reference the pre-computed dataset as a named RDD within jobserver, but due to the current implementation in spark.jobserver.JobServerNamedRdds, forceComputation defaults to true and cannot be overridden via the configuration.

Our question: was leaving out support for non-computed named RDDs a conscious design decision (in which case we'd be interested in understanding the reasoning behind), or an oversight?

**Comment by velvia** [comment]
Mike,

Hmm, this is a good point that NamedRDDs does not necessarily need to be
computed.  Changing the API so that the computation is not forced would be
pretty easy and I'm open to it.   If you're interested in working on a PR I
can help you, or file an issue and we'll get to it.

thanks,
Evan


On Tue, Sep 8, 2015 at 4:14 PM, Mike Janson <notifications@github.com>
wrote:

> Is there a reason why only *computed* named RDDs are currently supported?
>
> We have an extremely large (impossible to load into memory/disk) parquet
> dataset in AWS S3 which requires several minutes just to scan all partition
> files. We would like to reference the pre-computed dataset as a named RDD
> within jobserver, but due to the current implementation in
> spark.jobserver.JobServerNamedRdds, forceComputation defaults to true and
> cannot be overridden via the configuration.
>
> Our question: was leaving out support for non-computed named RDDs a
> conscious design decision (in which case we'd be interested in
> understanding the reasoning behind), or an oversight?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/247>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
Nevermind, this is already an issue.  Would be pretty easy for anyone to
pick up.

On Mon, Sep 14, 2015 at 4:03 PM, Evan Chan <velvia@gmail.com> wrote:

> Mike,
>
> Hmm, this is a good point that NamedRDDs does not necessarily need to be
> computed.  Changing the API so that the computation is not forced would be
> pretty easy and I'm open to it.   If you're interested in working on a PR I
> can help you, or file an issue and we'll get to it.
>
> thanks,
> Evan
>
>
> On Tue, Sep 8, 2015 at 4:14 PM, Mike Janson <notifications@github.com>
> wrote:
>
>> Is there a reason why only *computed* named RDDs are currently supported?
>>
>> We have an extremely large (impossible to load into memory/disk) parquet
>> dataset in AWS S3 which requires several minutes just to scan all partition
>> files. We would like to reference the pre-computed dataset as a named RDD
>> within jobserver, but due to the current implementation in
>> spark.jobserver.JobServerNamedRdds, forceComputation defaults to true and
>> cannot be overridden via the configuration.
>>
>> Our question: was leaving out support for non-computed named RDDs a
>> conscious design decision (in which case we'd be interested in
>> understanding the reasoning behind), or an oversight?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/spark-jobserver/spark-jobserver/issues/247>.
>>
>
>
>
> --
> If you are free, you need to free somebody else.
> If you have some power, then your job is to empower somebody else.
>    --- Toni Morrison
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by koettert** [comment]
We have just created a pull request (https://github.com/spark-jobserver/spark-jobserver/pull/269) for this issue that moves the parameters to the API to let the user decide if RDDs should be precomputed or not.

**Comment by velvia** [comment]
The patch has been merged to master, thanks to @noorul

**Comment by mjanson** [comment]
Thank you!

**Comment by noorul** [comment]
On Sep 9, 2015 4:44 AM, "Mike Janson" <notifications@github.com> wrote:
>
> Is there a reason why only computed named RDDs are currently supported?
>
> We have an extremely large (impossible to load into memory/disk) parquet
dataset in AWS S3 which requires several minutes just to scan all partition
files. We would like to reference the pre-computed dataset as a named RDD
within jobserver, but due to the current implementation in
spark.jobserver.JobServerNamedRdds, forceComputation defaults to true and
cannot be overridden via the configuration.
>

Well, now this can be overwritten. Take a look at reecent commit.

Thanks and Regards
Noorul

> Our question: was leaving out support for non-computed named RDDs a
conscious design decision (in which case we'd be interested in
understanding the reasoning behind), or an oversight?
