### ISSUE TITLE
Increase spray max content length in the app config

### ISSUE THREAD

**Issue by david-resnick** [spark-jobserver/spark-jobserver#27]
Current spray max-content-length of 8MB is too small to allow uploading fat jars.

This commit fixes it:
https://github.com/ooyala/spark-jobserver/pull/96/commits

**Comment by velvia** [comment]
Hey guys,

I already committed a fix as part of my new context support PR, increasing
it to 25MB I think.  The PR hasn't been merged yet though, anybody want to
have a look?

As for
adding an option for the content length, I think that's a great idea.

-Evan

On Mon, Jan 5, 2015 at 12:11 PM, Fernando Otero <notifications@github.com>
wrote:

> that should have been merged to spark-jobserver right?
>
> Another idea: how about changing server_start.sh and add something like
> SPRAY_OPTS = "-Dspray.can.parsing.max-content-length=200m"
>
> so it's configurable at deployment time, and one can change it without
> having to rebuild the project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/27#issuecomment-68770359>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by zeitos** [comment]
I took a look at that code and looks good to me, but I guess someone with more experience in scala and spark-jobserver should take another look

**Comment by velvia** [comment]
Thanks for the look!  Anybody else is welcome to look.

Here is the game plan moving forward:
- Add more tests and documentation
- Merge the PR
- Add 1.2.0 support (this might happen first, actually)
- Move the NamedRdds support out of its current place and into a special
context, so that NamedRdd support is no longer a special case

On Tue, Jan 6, 2015 at 4:49 AM, Fernando Otero <notifications@github.com>
wrote:

> I took a look at that code and looks good to me, but I guess someone with
> more experience in scala and spark-jobserver should take another look
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/27#issuecomment-68861146>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by velvia** [comment]
This can be closed now, max content length has been increased to 30MB, just merged.
