### ISSUE TITLE
Several masters to choose

### ISSUE THREAD

**Issue by ChenYanting** [spark-jobserver/spark-jobserver#314]
Hi 

In SJS configuration, we could assign several Spark masters. My scenario is that I have three data centers, A, B and C. Each of DCs has its own Spark cluster with 2 masters. I install one SJS in A data center. As a result, in the normal case the configuration of this SJS would looks like:

spark {
  master = "spark://A1:7077,A2:7077"
......

My question is that is it possible for me to let the SJS in A to connect to Spark masters in B data center in case that both masters in A are down?

In order to attain the goal, I want to configure it as:

spark {
  master = "spark://A1:7077,A2:7077,B1:7077,B2:7077,C1:7077,C2:7077"
......

**Comment by velvia** [comment]
@ChenYanting hmmm.   So the behavior with picking multiple masters is due to Spark, not SJS.  If you put both the A and B strings together in the master line, that won't do the multi-DC failover as you suggest.... though you could try it.  Also what you suggest only works with Spark standalone mode, not Mesos or YARN.

However there is a way to implement what you want.   You can implement a custom `SparkMasterProvider`; the default one just gets the master from the config string, but you can have one that picks from another datacenter if one fails.

Hope that answers the question.... and if you try out the above do let us know how it goes.
