### ISSUE TITLE
How to get result from streaming job

### ISSUE THREAD

**Issue by yanji84** [spark-jobserver/spark-jobserver#344]
I have a very simple streaming job to experiment with

```
object streaming extends SparkStreamingJob {
	override def runJob(ssc:StreamingContext, config: Config): Any = {
		val lines = ssc.socketTextStream("localhost", 19999)
		lines.print()
		ssc.start()
		ssc.awaitTermination()
	}
	override def validate(ssc:StreamingContext, config: Config): spark.jobserver.SparkJobValidation = SparkJobValid
}
```
Then I started this job asynchronously
```
curl 158.85.79.185:8090/jobs
[{
  "duration": "Job not done yet",
  "classPath": "com.projectx.jobserver.streaming",
  "startTime": "2015-12-13T01:07:15.430Z",
  "context": "streamquery",
  "status": "RUNNING",
  "jobId": "617be48b-f3bf-4e9c-bcad-4e932924c6ff"
}]
```
When I try to check the result from the job
```
curl 158.85.79.185:8090/jobs/617be48b-f3bf-4e9c-bcad-4e932924c6ff
{
  "status": "RUNNING"
}
```
only status is returned even though there are multiple lines of input at the console

**Comment by velvia** [comment]
Right now 
1) your runJob method returns nothing, as far as I can tell;
2) it would only return result when the context terminates, it’s probably because the streaming context does not terminate

You could test the termination with awaitTerminationOrTimeout().  However, is the job designed to terminate?  probably not right?

I think a better question is how to derive results from a streaming job, we need a stream of results.  But that’s a whole different discussion.

-Evan

**Comment by yanji84** [comment]
@velvia, if it is the case where a stream of results is expected, would jobserver be able to support this?

**Comment by velvia** [comment]
Right now no, but that is a really good feature request.  Want to file a PR?

**Comment by yanji84** [comment]
@velvia Sure since I am using Jobserver for one of my projects. I'll close this thread for now. Thanks for clarifying
