### ISSUE TITLE
Timeout exception on create context when a delete context operation is executed

### ISSUE THREAD

**Issue by blidiselalin** [spark-jobserver/spark-jobserver#466]
Steps to reproduce:

1. Create context <context-test-1>.
2. Delete context <context-test-1> and at the same time trigger another context <context-test-2> creation.  Check the logs and you can see that the context was created as expected, but the API call returns => "The server was not able to produce a timely response to your request."

NOTE: Spark-jobserver was deployed with spark.master = "yarn-client" and spark.jobserver.context-per-jvm = true
[timeoutException.txt](https://github.com/spark-jobserver/spark-jobserver/files/270606/timeoutException.txt)

**Comment by velvia** [comment]
Do you have any logs?
Have you guys tried increasing the timeout (see doc/troubleshooting.md)?

**Comment by blidiselalin** [comment]
The timeout was increased to 3 and then 5 minutes but without success. File timeoutException.txt from issue details contains the logs from spark-jobserver.

**Comment by CalebFenton** [comment]
There are three different timeouts to consider. The first two have to do with context creation:

1. context-creation-timeout
2. yarn-context-creation-timeout

Since you're using Yarn, I'm assuming you adjusted yarn-context-creation-timeout. I was having the same issue despite having adjusted this value to be quite high. The troublshooting documentation helpfully lists a _third_ timeout setting: spray.can.server.request-timeout. Adjusting this to something like 2 seconds would reliably reproduce the error. Adjusting it higher has prevented the error from recurring.

**Comment by blidiselalin** [comment]
Thanks for the input @CalebFenton. We had already set this timeout configurations but in order to fix our issue we had to change code on our fork branch to wait on context creation if a delete operation is in progress. In that way we don't receive any more exceptions or problems, it seems to be a hot fix for what we need right now.

**Comment by CalebFenton** [comment]
Good to know. I'll probably encounter a similar issue.

**Comment by noorul** [comment]
@blidiselalin Do you mind creating a PR with the patch?

**Comment by blidiselalin** [comment]
@noorul I can do that but from my point of view this is not a very nice fix because we have add a loop on context creation that checks with a thread sleep until the context is created as expected. This works for us but probably a better solution is to understand exactly how Akka Actors works why when a delete context operation is in progress you don't receive any status it hangs and throw a timeoutexception if you try to create another context.
