### ISSUE TITLE
HADR Question

### ISSUE THREAD

**Issue by farazstar333** [spark-jobserver/spark-jobserver#537]
How HADR (High availability and Disaster recovery ) is managed by Spark Job Server. Is it in mature state or still in progress?

**Comment by noorul** [comment]
This is still in progress. Mostly tracked by https://github.com/spark-jobserver/spark-jobserver/issues/42

**Comment by hntd187** [comment]
I think the job server has come a long way with its functionality but still is not 1.0. Evan and I spoke about it before and I agreed with him that 1.0 implies a certain level of production reliability which we think we're close to but there remains some work to do. It would be really nice to free ourselves from the spray and akka 2.3 requirements because that would let us use a lot of the nice work they've done in these areas but as such SJS is fine for production use you should just be aware it might be subject to some issues.

**Comment by noorul** [comment]
@farazstar333 If the answers are satisfactory, please close this issue.

**Comment by farazstar333** [comment]
Thanks. It answers my questions.
