### ISSUE TITLE
Spark Job Server - Akka Question

### ISSUE THREAD

**Issue by kishorez** [spark-jobserver/spark-jobserver#540]
Hi 

Can anyone point me to documentation or any link on how spark job server leverages akka tool kit and the usecases for which spark job server leverages the akka capabilities

Thanks
Kishore

**Comment by hntd187** [comment]
SJS uses both Spray (based on Akka) and Akka itself. Just read the code, we use akka and spray everywhere. Spray is for all of our Http Rest services and we use Akka internally to coordinate all the jobs and Spark Contexts as they run and allow it to be distributed and play nice.

This is an open source project so we don't really write down how we leverage certain technologies or use cases because the code is all there for you to read.

**Comment by velvia** [comment]
@kishorez you may also want to look in the doc/ folder, it has some (outdated) diagrams of how the actors are designed and their interactions.

**Comment by kishorez** [comment]
Thanks guys. I am troubleshooting the issue we ran into the limitation of 9 streaming job https://github.com/spark-jobserver/spark-jobserver/issues/533
I felt it has something to do with the akka configuration so I am trying to isolate the problem. A quick understanding of framework will help me to investigate faster. I believe when we enable context per JVM and I noticed we didn't put explicit configuration for akka and I think it is default. Looks like the addresses are getting conflicted so I am playing with the akka configurations
