### ISSUE TITLE
Question:What about separate htm from jar?

### ISSUE THREAD

**Issue by TianLangStudio** [spark-jobserver/spark-jobserver#556]
When we edit the front-end , we don't have to recompile the project to rebuild the jar? May be we can create a subdirectory named  web.

**Comment by noorul** [comment]
@TianLangStudio Can you coordinate with @baweaver? They are also working on UI part. I think it is better to have common direction.

**Comment by baweaver** [comment]
Likely what I'd end up doing is making it a completely separate project not hosted in the same repo. The thing I've found with a lot of these projects is that keeping the frontend ui separate from the backend server makes it far easier to work with long term.

Currently I'm thinking of going Angular due to its popularity and common libraries available.

**Comment by TianLangStudio** [comment]
@baweaver Yeah,That's good. You mean Angular2 ?

**Comment by baweaver** [comment]
For now likely 1.5x with a component style leaning towards TypeScript seeing as 2.x is (unless updated recently) still in RC.
