### ISSUE TITLE
Configuration of Kerberos in shiro.ini

### ISSUE THREAD

**Issue by Dom-nik** [spark-jobserver/spark-jobserver#632]
Hello,
Your README mentions supporting Kerberos, but I didn't find any examples of shiro.ini file to configure it.

I've also found an open JIRA regarding adding Kerberos support for Shiro (https://issues.apache.org/jira/browse/SHIRO-499) and browsed the project's site in detail looking for any hints regarding kerberos support (https://www.google.pl/search?q=site%3Ashiro.apache.org%2F+kerberos), but didn't find any information that would suggest that Shiro actually supports Kerberos.

On the other hand, some Jobserver users seem to be able to run it with Kerberos. What is the shiro.ini config that makes it work?

Thanks for your work!

**Comment by velvia** [comment]
According to the docs

https://cwiki.apache.org/confluence/display/SHIRO/Authentication+Features

it is supported….  

@TimMaltGermany do you have any ideas?

-Evan

**Comment by Dom-nik** [comment]
I got a following answer from KNIME support (they use Spark Job Server for their Spark Executor):
> The Kerberos support of the Spark Job Server means that the Spark Job Server can create Spark contexts for users within a secured cluster using the proxy-user flag when issuing the spark-submit command that creates the context.

I don't understand it fully yet, does it mean that Spark Jobserver actually suprasses Shiro when working with a Kerberos-enabled cluster? The bottom line for me is: how should I configure shiro.ini (and any other required configs) to be able to run Spark Jobserver on a Kerberos-enabled cluster.

**Comment by velvia** [comment]
I would ask them for more details, and share it here.  I’m curious to know too.  :-p

**Comment by koettert** [comment]
Let me try to clarify this. There are two parts to this. 
The first part is the authentication of users against the Spark job server to only allow authenticated users to submit and managed jobs using the Spark Job Server. For this part Apache Shiro is used which allows for example basic user authentication via a user name and password [file](https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/config/shiro.ini.basic.template) or via [LDAP](https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/config/shiro.ini.ldap.template). This is independent of your Hadoop cluster setup e.g.  secured or unsecured.

The second part is the submission of Spark jobs when you have a Kerberos secured cluster. To do so the Spark Job Server uses the [proxy-user](https://www.cloudera.com/documentation/enterprise/5-5-x/topics/sg_spark_auth.html) flag when executing the spark-submit command. To do so the os user that runs the Spark Job Server needs to have a valid Kerberos ticket. Since the user will run Spark jobs on behalf of other users it needs the [impersonate](https://hadoop.apache.org/docs/r1.2.1/Secure_Impersonation.html) right. The Spark Job Server that comes with KNIME takes care of the Kerberos ticket via a shell script that renews the Kerberos ticket using a provided keytab file. This is described in the _How to install on a Kerberos-secured cluster_ section in the [KNIME installation manual](https://www.knime.org/files/documentation/big-data/knime_spark_executor_installation_guide_1.6.0.pdf).

When submitting the spark-submit command the name of the user that is logged into the Spark Job Server via Shiro is used as proxy-user. That is why the use-as-proxy-user option is part of the shiro configuration in the environment.conf file. Also the context-per-jvm flag in the environment.conf file needs to be enable if you want to connect to a secured cluster to ensure that every user has its own Spark context that runs with the rights of the user.

**Comment by velvia** [comment]
Tobias, many thanks.  Do you mind if we post a version of this to our docs?

**Comment by Dom-nik** [comment]
Thank you a lot @koettert ! It clarifies a lot! I think that mentioning this in your docs could be beneficial to other users too.

I have three more detailed questions regarding your response. They cover some corner cases, but these cases are exactly the problems that I'll be facing with my installation: 
> To do so the os user that runs the Spark Job Server needs to have a valid Kerberos ticket.

1. Does the os user have to be named the same as the Kerberos user that the keytab is for?

> When submitting the spark-submit command the name of the user that is logged into the Spark Job Server via Shiro is used as proxy-user.

2. If I understand things right, this means that if I use LDAP in Shiro part, I would have to have an application user in Kerberos that is named exactly the same as a user existing in LDAP. Am I right?
3. On the other hand, if I decide to use the simple user-based authentication in Shiro, but have a secured cluster, I can setup only one user (application user) that will be the proxy user used for impersonation, because the rest will be handled by Kerberos. Is that true? Does the name of this user matter and have to be the same as os user name?

Sorry for loads of questions, but this seemingly simple application turns out to have a lot of details to consider...

**Comment by koettert** [comment]
> Does the os user has to be named the same as the Kerberos user that the keytab is for?
No the users can be different but the os user needs to have access to the Kerberos ticket. If it is different you need to specify the Kerberos user as JOBSERVER_PRINCIPAL as described in the [manual](https://www.knime.org/files/documentation/big-data/knime_spark_executor_installation_guide_1.6.0.pdf). If the principle is not defined a Kerberos principal is generated based on the os user, the host name and the default principle in the krb5.conf file. For details see the kerberos-ticket-renewer.sh file in the [KNIME Spark Job server installation](https://www.knime.org/knime-spark-executor#install).

> If I understand things right, this means that if I use LDAP in Shiro part, I would have to have an application user in Kerberos that is named exactly the same as a user existing in LDAP. Am I right?
Yes that is correct. The job server is using the Shiro authenticated user name as proxy user in the spark-submit command. The idea behind this is that if LDAP is used we thought that it is usually also used as the user database for the Kerberos Server and thus the users are the same.

> On the other hand, if I decide to use the simple user-based authentication in Shiro, but have a secured cluster, I can setup only one user (application user) that will be the proxy user used for impersonation, because the rest will be handled by Kerberos. Is that true?
What do you mean with the rest is handled by Kerberos?
You will need to create an entry for each user you want to impersonate in the Shiro user file and you will always need a Kerberos user that has the right to impersonate all of these users.

>Does the name of this user matter and have to be the same as os user name?
Same as the first question since it is the Kerberos user the Spark Job server is using for impersonation it does not need to be the os user but the os user needs to have access to the Kerberos ticket.

Maybe an example explains it better:
We have to users UserA and UserB that want to run Spark jobs via the Spark Job Server on a secured cluster. Each user has a Kerberos principal such as UserA@DOMAIN and UserB@DOMAIN. With simple authentication we would create a Shiro Username/Password file like
UserA pwd1
UserB pwd2
In addition we need a Kerberos principal e.g. sparkJobServer@DOMAIN that has the right to impersonate other users. 
Before starting the Spark Job Server we obtain a Kerberos ticket for the sparkJobServer@DOMAIN via kinit (This is what the kerberos-ticket-renewer.sh file is doing if you set it up). When UserA now wants to start a Spark job he needs to authenticate himself against Shiro with login UserA and password pwd1. Once authenticated the Spark Job Server creates a new Spark context via the spark-submit command with UserA as proxy user. In doing so the Spark Job Server authenticates itself via the Kerberos ticket for the sparkJobServer@DOMAIN principal. Thus the Spark context is created using the sparkJobServer@DOMAIN Kerberos user but it is running with the rights of the UserA@DOMAIN Kerberos user.

**Comment by noorul** [comment]
Closing this!
