### ISSUE TITLE
No logs for contexts in forked JVMs

### ISSUE THREAD

**Issue by basvandenbrink** [spark-jobserver/spark-jobserver#739]
When setting `context-per-jvm = true`, logging does not got to STD_OUT, even in the Docker image. Instead, logging should go to `/tmp/job-server/<context_name><random_id>`. However, there is only a `context.conf` file in that folder while running that job, no logging file. I am running version 0.6.2. in Docker.

**Comment by noorul** [comment]
I would create a separate docker image to override default one and would have something like this 

    RUN ln -sf /proc/1/fd/1 /var/log/spark-jobserver/spark-jobserver.log

and would override log4j-server.properties with 

    # Rotating log file configuration for server deploys
    
    # Root logger option
    
    log4j.rootLogger=${LOG_LEVEL},LOGFILE
    
    log4j.logger.org.spark-project.jetty=WARN
    log4j.logger.org.spark-project.jetty.util.component.AbstractLifeCycle=ERROR
    log4j.logger.org.apache.spark.repl.SparkIMain$exprTyper=WARN
    log4j.logger.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter=WARN
    log4j.logger.org.apache.parquet=ERROR
    log4j.logger.parquet=ERROR
    
    log4j.logger.org.apache.hadoop.hive.metastore.RetryingHMSHandler=FATAL
    log4j.logger.org.apache.hadoop.hive.ql.exec.FunctionRegistry=ERROR
    
    log4j.appender.LOGFILE=org.apache.log4j.FileAppender
    log4j.appender.LOGFILE.File=/var/log/spark-jobserver/spark-jobserver.log
    log4j.appender.LOGFILE.layout=org.apache.log4j.PatternLayout
    log4j.appender.LOGFILE.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: [%X{akkaSource}] - %m%n

**Comment by basvandenbrink** [comment]
According to the [`log4j-server.properties`](https://github.com/spark-jobserver/spark-jobserver/blob/v0.6.2/job-server/config/log4j-server.properties) file, the logs should already go to a file inside the Docker container. The log directory itself is defined in [this class](https://github.com/spark-jobserver/spark-jobserver/blob/v0.6.2/job-server/src/spark.jobserver/AkkaClusterSupervisorActor.scala#L243). By the way, the pattern for the directory is `/tmp/job-server/jobserver-<encodedContextName>`. So I would say that the `log4j-server.properties` file isn't picked up correctly, but I can't tell why. The log configuration file is passed by [`manager_start.sh`](https://github.com/spark-jobserver/spark-jobserver/blob/v0.6.2/bin/manager_start.sh#L17), so it should be fine.

Instead, logs go to `STD_OUT`. I figured that out by modifying the last line of `manager_start.sh`:
```
eval $cmd > $1/custom_log.log 2>&1 &
```

**Comment by noorul** [comment]
@basvandenbrink Shall we close this issue?

**Comment by basvandenbrink** [comment]
Actually, I don't think it is fixed. My modification is only a temporary hack.

**Comment by fmcgough** [comment]
Agreed, I have just spent several hours trying to debug this issue. The behaviour I would expect for multiple contexts running in a Docker container is for all of their logs to go to std out. The combination of the default `manager_start.sh` script putting the process in the background, and the behaviour [here](https://github.com/spark-jobserver/spark-jobserver/blob/v0.6.2/job-server/src/spark.jobserver/AkkaClusterSupervisorActor.scala#L223) which waits for the script to exit before deciding if the context has been created successfully, means that it's impossible to achieve this with the standard docker file - if you use a script which keeps the process in the foreground, the method will never complete, but if not, the log output will be lost when the script exits. Some kind of config flag to determine whether you expect the process to exit immediately or not might be helpful here.

**Comment by bsikander** [comment]
manager_start.sh is replaced with SparkLauncher, please reopen the issue if the problem persists. Closing.

**Comment by mac-kapil** [comment]
Hi , 
I am getting same issue with 0.10.1 version having sparkLauncher instead of manager_start.sh .
I an trying to direct context logs to docker container logs and provided below log4j.properties 


# Set everything to be logged to the console
log4j.rootCategory=WARN, console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.target=System.out
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yyyy/MM/dd HH:mm:ss} %p %c{6}: %m%n


: ${MANAGER_LOGGING_OPTS:="-Dlog4j.configuration=file:/spark/conf/log4j.properties"} in setenv.sh 

but still getting context logs on  on /tmp/jobserver<encoding>/spark-job-server.out .. 
but we need on container logs as well .


job submitted by ManagerLauncher 
org.apache.spark.deploy.SparkSubmit --master spark://spark-master:7077 --deploy-mode client --conf spark.driver.memory=1g --conf spark.master.rest.enabled=true --conf spark.executor.extraJavaOptions=-Dlog4j.configuration=file:/spark/conf/log4j.properties  --conf spark.driver.extraJavaOptions=-XX:+UseConcMarkSweepGC -verbose:gc -XX:-PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:MaxPermSize=512m -XX:+CMSClassUnloadingEnabled -Xloggc:/tmp/jobserver2465320055439465947/gc.out -XX:MaxDirectMemorySize=512M -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Dlog4j.configuration=file:/spark/conf/log4j.properties -DLOG_DIR=/tmp/jobserver2465320055439465947 --class spark.jobserver.JobManager --name scala-context1  akka.tcp://JobServer@127.0.0.1:38991 jobManager-518334dd-9aa0-42f2-9e0a-7c6319f06145 file:/spark/job-server/jobserver.conf
