### ISSUE TITLE
error while Compiler spark-jobserver

### ISSUE THREAD

**Issue by EthernH** [spark-jobserver/spark-jobserver#957]
**Used Spark version**
2.2.0
**Used Spark Job Server version**
(Released version, git branch or docker image version)
0.8.0
**Deployed mode**
(client/cluster on Spark Standalone/YARN/Mesos/EMR or default)

**Actual (wrong) behavior**

**Steps to reproduce**

**Logs**

```
some log
```
deduplicate: different file contents found in the following:
/home/han.xin.o/.ivy2/cache/io.netty/netty-all/jars/netty-all-4.0.44.Final.jar:io/netty/channel/nio/AbstractNioByteChannel$1.class
/home/han.xin.o/.ivy2/cache/io.netty/netty-transport/jars/netty-transport-4.0.47.Final.jar:io/netty/channel/nio/AbstractNioByteChannel$1.class

error   /home/han.xin.o/.ivy2/cache/io.netty/netty-all/jars/netty-all-4.0.44.Final.jar:io/netty/util/internal/shaded/org/jctools/util/Pow2.class    
 error   /home/han.xin.o/.ivy2/cache/io.netty/netty-common/jars/netty-common-4.0.47.Final.jar:io/netty/util/internal/shaded/org/jctools/util/Pow2.class    
 error   deduplicate: different file contents found in the following:    
 error   /home/han.xin.o/.ivy2/cache/io.netty/netty-all/jars/netty-all-4.0.44.Final.jar:io/netty/util/internal/shaded/org/jctools/util/UnsafeAccess.class    
 error   /home/han.xin.o/.ivy2/cache/io.netty/netty-common/jars/netty-common-4.0.47.Final.jar:io/netty/util/internal/shaded/org/jctools/util/UnsafeAccess.class    

Unused parts of this template should be removed (including this line).

**Comment by tropicalpb** [comment]
We also get this error during  sbt assembly on the latest master.  Is there a workaround.  Thanks

**Comment by velvia** [comment]
Hmm.  I just pulled the latest and did the following:

sbt
> project job-server-extras
> assembly

and it completed fine.  Is that what you guys did?

**Comment by tropicalpb** [comment]
We ran sbt clean assembly and sbt "set test : = {}" clean assembly

**Comment by noorul** [comment]
sbt job-server-extras/assembly

**Comment by tropicalpb** [comment]
sbt job-server-extras/assembly does seem to do the trick.  thanks

**Comment by velvia** [comment]
Hmmm.  I’ll look into disabling job-server/assembly.

Evan Chan
velvia@gmail.com
----
“Never doubt that a small group of thoughtful, committed citizens can change the world.” —M. Mead

**Comment by velvia** [comment]
See PR #959
https://github.com/spark-jobserver/spark-jobserver/pull/959

for disabling job-server/assembly

**Comment by tropicalpb** [comment]
sorry, I figured out.  I had the manager_start.sh mixed from the old
version.  sigh....

**Comment by velvia** [comment]
Ah.  Glad to hear you figured it out.   It’s always better to do a clean sync  :)

**Comment by tropicalpb** [comment]
well, now i have a legimate issue that looks like

when I set sync=false, job server api just hangs and not returning an job
id, even though

**Comment by tropicalpb** [comment]
well, now i have a legimate issue that looks like
https://github.com/spark-jobserver/spark-jobserver/issues/898

when I set sync=false, job server api just hangs and not returning an job
id, even though I can clearly see from the job server 8090 port web console
that job completes successfully (it only took less than 2 seconds); when I
set sync=true, job returns fine.

$ curl -X POST -d
'sparkjob.configuration="{&quot;sparkjob.input.connectors&quot;:&quot;HDFSInputConnector?id=c4,output=c6(input.path=&#96;/user/nio1/demo1/data&#96;,input.format=&#96;csv&#96;,data.schema=&#96;t1
int, t2
int&#96;)&quot;,&quot;sparkjob.output.connectors&quot;:&quot;HDFSOutputConnector?id=c7,input=c8(output.path=&#96;/user/nio1/demo1/result&#96;)&quot;,&quot;sparkjob.analytic.operations&quot;:&quot;Project?input=c6,output=c8()&quot;}"'
'
http://10.132.64.9:8090/jobs?appName=ac&classPath=com.exceeddata.ac.job.runner.SparkJobRunner&context=acweb&sync=false
'
{
  "status": "ERROR",
  "result": {
    "message": "Ask timed out on
[Actor[akka://JobServer/user/job-info#267019317]] after [60000 ms].
Sender[null] sent message of type
\"spark.jobserver.JobInfoActor$StoreJobConfig\".",
    "errorClass": "akka.pattern.AskTimeoutException",
    "stack": "akka.pattern.AskTimeoutException: Ask timed out on
[Actor[akka://JobServer/user/job-info#267019317]] after [60000 ms].
Sender[null] sent message of type
\"spark.jobserver.JobInfoActor$StoreJobConfig\".\n\tat
akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)\n\tat
akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)\n\tat
scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)\n\tat
scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)\n\tat
scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)\n\tat
akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:331)\n\tat
akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:282)\n\tat
akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:286)\n\tat
akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:238)\n\tat
java.lang.Thread.run(Thread.java:748)\n"
  }

$ curl -X POST -d
'sparkjob.configuration="{&quot;sparkjob.input.connectors&quot;:&quot;HDFSInpuConnector?id=c4,output=c6(input.path=&#96;/user/nio1/demo1/data&#96;,input.format=&#96;csv&#96;,data.schema=&#96;t1
int, t2
int&#96;)&quot;,&quot;sparkjob.output.connectors&quot;:&quot;HDFSOutputConnector?id=c7,input=c8(output.path=&#96;/user/nio1/demo1/result&#96;)&quot;,&quot;sparkjob.analytic.operations&quot;:&quot;Project?input=c6,output=c8()&quot;}"'
'
http://10.132.64.9:8090/jobs?appName=ac&classPath=com.exceeddata.ac.job.runner.SparkJobRunner&context=acweb&sync=true
'
{
  "jobId": "76966f8b-f6f6-4393-a1ce-2233388432be",
  "result": 0
}

**Comment by tropicalpb** [comment]
here is the relevant settings, i didn't find anything in the
/var/log/job-server/job-server....id that is of any useful info.

jobserver {
 17     port = 8090
 18
 19     context-per-jvm = true
 20     short-timeout = 60s
 21     max-jobs-per-context = 4
 22     jar-store-rootdir = /opt/exd-3.0/spark-jobserver-0.8.0/jars
 23
 24     # Note: JobFileDAO is deprecated from v0.7.0 because of issues in
 25     # production and will be removed in future, now defaults to H2 file.
 26     jobdao = spark.jobserver.io.JobSqlDAO
 27
 28     filedao {
 29       rootdir = /opt/exd-3.0/spark-jobserver-0.8.0/filedao/data
 30     }
 31
 32     datadao {
 33       # storage directory for files that are uploaded to the server
 34       # via POST/data commands
 35       rootdir = /opt/exd-3.0/spark-jobserver-0.8.0/datadao/upload
 36     }
 37
 38     sqldao {
 39       # Slick database driver, full classpath
 40       slick-driver = slick.driver.H2Driver
 41
 42       # JDBC driver, full classpath
 43       jdbc-driver = org.h2.Driver
 44
 45       # Directory where default H2 driver stores its data. Only needed
for H2.
 46       rootdir = /opt/exd-3.0/spark-jobserver-0.8.0/sqldao/data
 47
 48       # Full JDBC URL / init string, along with username and password.
Sorry, needs to match above.
 49       # Substitutions may be used to launch job-server, but leave it
out here in the default or tests won't pass
 50       jdbc {
 51         url =
"jdbc:h2:file:/opt/exd-3.0/spark-jobserver-0.8.0/sqldao/data/h2-db"
 52         user = ""
 53         password = ""
 54       }
 55
 56       # DB connection pool settings
 57       dbcp {
 58         enabled = false
 59         maxactive = 20
 60         maxidle = 10
 61         initialsize = 10
 62       }
 63     }
 64     # When using chunked transfer encoding with scala Stream job
results, this is the size of each chunk
 65     result-chunk-size = 1m
 66   }

**Comment by tropicalpb** [comment]
sigh, turns out I need the secret/secret user/pass.  It'd be nice if
there's more logging to make this more obvious.

**Comment by velvia** [comment]
Hm, I guess you need authentication then?

So, can we close this ticket?

**Comment by tropicalpb** [comment]
my issues are over. :-)
